use clap::CommandFactory;
use copit::cli::Args;
use std::fs;

fn main() {
    let markdown = clap_markdown::help_markdown_command(&Args::command());
    let content = format!(
        "<!-- This file is auto-generated by `cargo run --bin generate_cli_docs`. Do not edit manually. -->\n\n{markdown}"
    );
    fs::write("docs/commands.md", content).expect("failed to write docs/commands.md");
    println!("Generated docs/commands.md");
}
